### ISSUE TITLE
Tableau resets the filters after some inactivity

### ISSUE THREAD

**Issue by Hunter-Github** [donnemartin/viz#15]
ESR Firefox 38.6.0, I selected 'C#' and waited a minute or so, then the graph reset to 'All languages'.

**Comment by donnemartin** [comment]
Hi, this seems to be the issue you're describing:

https://community.tableau.com/thread/170831

Unfortunately I don't think I have control over with the hosted Tableau Public visualization.

One option is to viz offline with the reader: 

https://github.com/donnemartin/viz#can-i-viz-offline

**Comment by Hunter-Github** [comment]
Thanks. Not a nice feature from Tableau; you could either close the issue or leave it open with a tag.

**Comment by donnemartin** [comment]
I updated the FAQ:

https://github.com/donnemartin/viz#why-does-the-online-viz-reset-after-several-minutes-of-inactivity
