### ISSUE TITLE
Add Julia to the list of languages

### ISSUE THREAD

**Issue by ScottPJones** [donnemartin/viz#18]
Although this is a fairly new language, and is not yet at a 1.0 release (currently at v0.4.3), there is a growing community around it (JuliaLang, JuliaOpt, BioJulia, JuliaDB, JuliaStats and many other organizations, along with many individual repos).

**Comment by donnemartin** [comment]
Sounds good, thanks for the suggestion. I'll put this in for the rolling 6-, 3-, and 1-month visualizations under development.
